#src = "z:\"
src = "c:\Users\Vyacheslav\Downloads\vid\"

src = src + "\Welcome to the official CD PROJEKT RED Twitch channel!-v302423092.mp4"
src = ffmpegsource2(src)
#alphabet = ImageSource("c:\Users\Vyacheslav\source\repos\ssifSource\TextDecode\alphabet.png")

offset=0 #17188+424-100
#src = src.Trim(offset,1834151+17188)

#LoadPlugin(".\TextDecode.dll")
#LoadPlugin("c:\Users\Vyacheslav\source\repos\ssifSource\__build\TextDecode\Release\TextDecode.dll")
#TextDecode(src, alphabet, offset)
src
